name: 'Generate mutation report'
description: 'Parses Stryker-Output content and aggregates final report'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  name:
    description: 'Check run name'
    required: true
  check-run-id:
    description: 'Id of check run that was started for mutation testing'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
